function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?Object.assign(structuredClone(DEFAULT),x,{world:Object.assign({},DEFAULT.world,x.world||{}),observations:x.observations||{}}):structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
let S=load();
const grade=x=>x>=.8?'A':x>=.6?'B':x>=.4?'C':'D';
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function traits(h){return[h.ri>=.7?'大胆':h.ri<=.35?'慎重':'中庸',h.co>=.75?'仲間を重視':h.co<=.35?'自己判断を優先':'協調型',h.d>=.75?'方針を重視':h.d<=.35?'現場判断型':'柔軟']}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='mission')renderMission();if(id==='roster')renderRoster();if(id==='formation')renderFormation();if(id==='aar')renderAAR();scrollTo(0,0)}
function trackHtml(frontier,known,reached=null){const ks=new Set(known||[]),cells=[];for(let i=1;i<=10;i++){const cls=['sector'];if(i<=frontier)cls.push('route');else if(ks.has(i))cls.push('survey');if(reached===i)cls.push('reached');cells.push(`<div class="${cls.join(' ')}">${i}</div>`)}return`<div class="sector-track">${cells.join('')}</div><div class="track-legend"><span>■ 補給路運用可能</span><span>□ 調査情報あり</span>${reached?'<span>● 今回の最深到達</span>':''}</div>`}
function missionHtml(f){const sv=surveyed(S.world.known);return`${trackHtml(f,S.world.known)}<div class="kpis"><div class="kpi">補給路運用可能<b>Sector 1–${f}</b></div><div class="kpi">調査済み<b>Sector 1–${sv}</b></div><div class="kpi">北部安定輸送能力<b>${transport(f)}%</b></div><div class="kpi">北部集落 生活備蓄見込み<b>${reserve(f).toFixed(1)}か月</b></div></div><div class="summary"><b>現在のボトルネック:</b> ${bottleneck(f)}<br><span class="small">北部集落まで連続して補給路が成立するまで、安定輸送能力と生活備蓄見込みは改善しない。</span></div>`}
function renderMission(){missionState.innerHTML=missionHtml(S.world.frontier);risk.value=S.risk;priority.value=S.priority}
function obs(h){return S.observations[h.id]?`<div class="small"><b>最近:</b> ${S.observations[h.id]}</div>`:'<div class="small">まだ十分な行動履歴がない。</div>'}
function card(h,sel=false){return`<button class="card hero ${sel&&S.sel.includes(h.id)?'selected':''}" ${sel?`onclick="toggleHero('${h.id}')"`:''}><b>${h.n}</b><div class="tags">${traits(h).map(x=>`<span class="tag">${x}</span>`).join('')}</div>戦闘 ${grade(h.c)} / 探索 ${grade(h.e)} / 粘り ${grade(h.r)}${obs(h)}</button>`}
function renderRoster(){rosterGrid.innerHTML=HEROES.map(h=>card(h)).join('')}
function toggleHero(id){if(S.sel.includes(id)){if(S.sel.length>1)S.sel=S.sel.filter(x=>x!==id)}else if(S.sel.length<4)S.sel.push(id);if(!S.sel.includes(S.leader))S.leader=S.sel[0];save();renderFormation()}
function renderFormation(){formationGrid.innerHTML=HEROES.map(h=>card(h,true)).join('');leader.innerHTML=S.sel.map(id=>`<option value="${id}">${hero(id).n}</option>`).join('');leader.value=S.leader;leader.onchange=()=>{S.leader=leader.value;save();renderFormation()};const p=S.sel.map(hero);partySummary.innerHTML=`選択 ${p.length}/4　隊長: ${hero(S.leader)?.n||'-'}<br><span class="small">平均能力 — 戦闘 ${grade(p.reduce((z,h)=>z+h.c,0)/p.length)} / 探索 ${grade(p.reduce((z,h)=>z+h.e,0)/p.length)} / 粘り ${grade(p.reduce((z,h)=>z+h.r,0)/p.length)}</span>`;startBtn.disabled=p.length!==4}
function startRun(){if(S.sel.length!==4)return;S.risk=risk.value;S.priority=priority.value;const r=simulate();S.runs=r.runId;S.last=r;save();renderExpedition(r);aarBtn.disabled=false;go('expedition')}
function renderExpedition(r){runHead.innerHTML=`<b>北部補給路の確立</b><br>補給路運用可能 Sector 1–${r.frontierBefore} / 目標 Sector 10<br>隊長 ${hero(r.leader).n} / ${r.risk} / ${r.priority}`;eventLog.innerHTML=r.events.map(x=>{const a=x.d.adv.slice().sort((p,q)=>q.w-p.w)[0],status=x.safe?'<span class="pill">補給路条件を満たす</span>':'<span class="pill">調査情報のみ</span>';return`<div class="card"><h3>Sector ${x.sector} — ${x.e.title}</h3><div class="proposals">${r.party.map(id=>`<div class="proposal"><b>${hero(id).n}</b><br>${LABEL[x.prs[id].a]}</div>`).join('')}</div><div class="decision"><b>隊長判断: ${LABEL[x.d.pick]}</b><br><span class="small">主要助言: ${a?hero(a.id).n+' '+LABEL[a.a]:'なし'} / ${x.o.proc}</span></div><div class="outcome">結果: <b>${x.o.cls}</b>　携行物資 -${x.cost}% ${status}<br><span class="small">残携行物資 ${x.suppliesAfter}% / ${x.o.variance}</span></div></div>`}).join('')}
function delta(a,b,s=''){return`<span class="before">${a}${s}</span><span class="arrow">→</span><span class="after">${b}${s}</span>`}
function changes(r){const ch=r.events.flatMap(e=>e.changes||[]),t=ch.filter(x=>x.type==='trust'),xp=ch.filter(x=>x.type==='xp');let h='';for(const x of t.slice(0,5))h+=`<div class="small">${hero(x.from).n}は${hero(x.to).n}の「${LABEL[x.evidence]}」という助言を${x.delta>0?'以前より信頼':'やや疑問視'}した。</div>`;for(const id of [...new Set(xp.map(x=>x.id))].slice(0,5))h+=`<div class="small">${hero(id).n}は今回の状況から経験を得た。</div>`;return h||'<span class="small">目立った人物変化はなかった。</span>'}
function causalHtml(r){const spent=100-r.suppliesLeft,routeGain=r.frontierAfter-r.frontierBefore,infoGain=[...new Set([...r.safeNew,...r.knownNew])].length,connected=r.frontierAfter>=10;const direct=connected?`北部安定輸送能力 ${delta(r.transportBefore,r.transportAfter,'%')}<br>北部集落 生活備蓄見込み ${delta(r.reserveBefore.toFixed(1),r.reserveAfter.toFixed(1),'か月')}`:`北部安定輸送能力 ${r.transportAfter}%（変化なし）<br>北部集落 生活備蓄見込み ${r.reserveAfter.toFixed(1)}か月（変化なし）<div class="separate-note">理由: ${r.bottleneckAfter} が残り、End-to-End輸送のボトルネックが解消していない。</div>`;const next=connected?'Sector 10まで連続した補給路が成立。北部集落への安定輸送が改善した。':`次回は既確立区間を再攻略せず、Sector ${r.frontierAfter+1}以降の未確立区間に集中できる。`;return`<div class="causal"><div class="cause-step"><b>今回払ったもの</b><br>遠征携行物資 ${spent}% 消費${r.injuries.length?' / 負傷 '+r.injuries.map(id=>hero(id).n).join('、'):' / 負傷なし'}<div class="separate-note">携行物資は今回の遠征継続余力。北部集落の生活備蓄とは別勘定。</div></div><div class="cause-arrow">↓</div><div class="cause-step"><b>今回作ったもの</b><br>補給路運用可能 +${routeGain} Sector / 新規調査情報 ${infoGain} Sector</div><div class="cause-arrow">↓</div><div class="cause-step"><b>北部集落への直接効果</b><br>${direct}</div><div class="cause-arrow">↓</div><div class="cause-step"><b>${connected?'Mission効果':'次回遠征への恒久効果'}</b><br>${next}</div></div>`}
function renderAAR(){const r=S.last;if(!r){aarRoot.innerHTML='<div class="summary">まだ遠征結果がない。</div>';return}const ni=[...new Set([...r.safeNew,...r.knownNew])].sort((a,b)=>a-b),cls=r.result==='SUCCESS'?'good':r.result==='FAILURE'?'bad':'';aarRoot.innerHTML=`<div class="result ${cls}"><span class="small">MISSION RESULT</span><h2>${r.result}</h2><b>北部補給路をSector 10まで運用可能にする</b>${trackHtml(r.frontierAfter,r.knownAfter,r.reached)}<div class="kpis"><div class="kpi">遠征到達<b>Sector ${r.reached}</b></div><div class="kpi">調査済み<b>${delta('Sector '+r.surveyedBefore,'Sector '+r.surveyedAfter)}</b></div><div class="kpi">補給路運用可能<b>${delta('Sector 1–'+r.frontierBefore,'Sector 1–'+r.frontierAfter)}</b></div><div class="kpi">北部安定輸送能力<b>${delta(r.transportBefore,r.transportAfter,'%')}</b></div></div><p><b>北部集落 生活備蓄見込み:</b> ${delta(r.reserveBefore.toFixed(1),r.reserveAfter.toFixed(1),'か月')}</p><p><b>残るボトルネック:</b> ${r.bottleneckAfter}</p><p>新規情報: ${ni.length?ni.map(s=>'Sector '+s).join(', '):'なし'}</p></div><div class="card"><h3>今回のコスト → 効果</h3>${causalHtml(r)}</div><div class="card"><h3>Key Decisions</h3>${r.events.map(x=>`<div class="row"><span>S${x.sector} ${x.e.title}</span><span>${LABEL[x.d.pick]} → ${x.o.cls}${x.safe?' → 補給路条件成立':' → 調査情報のみ'}</span></div>`).join('')}</div><div class="card"><h3>Personal Appraisal</h3><p class="small">以下は客観的Resultではなく各人物の受け止め。</p>${r.appraisals.map(a=>`<div class="appraisal"><b>${hero(a.id).n}</b><br>「${a.text}」</div>`).join('')}</div><div class="card"><h3>Persistent Human Changes</h3>${changes(r)}</div>`;debug.textContent=JSON.stringify({state:S,last:r},null,2)}
function saveMemo(){const t=memo.value.trim();if(!t)return;S.memos.push({run:S.runs,text:t,at:new Date().toISOString()});save();memo.value='';saved.textContent='保存済み'}
function resetPrototype(){if(!confirm('MFP02.2の検証状態を初期化しますか？'))return;localStorage.removeItem(KEY);S=structuredClone(DEFAULT);renderMission();renderRoster();renderFormation();aarRoot.innerHTML='';go('mission')}
renderMission();renderRoster();renderFormation();if(S.last)aarBtn.disabled=false;
